server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/lesson_cloud?characterEncoding=UTF-8
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: 123456
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create