server:
  port: 80

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/lesson_cloud?characterEncoding=UTF-8
    username: root
    password: 981214
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    open-in-view: false