gzmu:
  generate:
    version: 1.0
    database:
      url: jdbc:mysql://127.0.0.1:3306/lesson-cloud
      username: root
      password: 123456
      driver-class-name: com.mysql.cj.jdbc.Driver
      catalog: lesson-cloud
      base-field: id, name, spell, sort, create_user_name, create_time, last_update_user_name, last_update_time, remark, is_enable, create_time, modify_time, create_user, modify_user
      exclude-table: UserConnection
    entity:
      package-name: cn.edu.gzmu.model.entity
      base-entity: cn.edu.gzmu.model.BaseEntity
      module-name: lesson-cloud-model
      where-clause: is_enable = 1
      overwrite: true
    repository:
      package-name: cn.edu.gzmu.repository.entity
      base-repository: cn.edu.gzmu.repository.BaseRepository
      module-name: lesson-cloud-repository
      overwrite: false
    controller:
      package-name: cn.edu.gzmu.controller
      base-controller: cn.edu.gzmu.controller.BaseController
      module-name: lesson-cloud-core
      overwrite: true
    service:
      package-name: cn.edu.gzmu.service
      base-service: cn.edu.gzmu.base.BaseService
      base-service-impl: cn.edu.gzmu.base.impl.BaseServiceImpl
      module-name: lesson-cloud-service
      overwrite: true
    gen-controller: true
    gen-repository: true
    gen-entity: true
    gen-service: true
